// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.8
// source: video.proto

package video

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoClient interface {
	Info(ctx context.Context, opts ...grpc.CallOption) (Video_InfoClient, error)
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type videoClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoClient(cc grpc.ClientConnInterface) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) Info(ctx context.Context, opts ...grpc.CallOption) (Video_InfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Video_ServiceDesc.Streams[0], "/Video/Info", opts...)
	if err != nil {
		return nil, err
	}
	x := &videoInfoClient{stream}
	return x, nil
}

type Video_InfoClient interface {
	Send(*InfoRequest) error
	Recv() (*InfoResponse, error)
	grpc.ClientStream
}

type videoInfoClient struct {
	grpc.ClientStream
}

func (x *videoInfoClient) Send(m *InfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *videoInfoClient) Recv() (*InfoResponse, error) {
	m := new(InfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *videoClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/Video/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
// All implementations must embed UnimplementedVideoServer
// for forward compatibility
type VideoServer interface {
	Info(Video_InfoServer) error
	Push(context.Context, *PushRequest) (*InfoResponse, error)
	mustEmbedUnimplementedVideoServer()
}

// UnimplementedVideoServer must be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (UnimplementedVideoServer) Info(Video_InfoServer) error {
	return status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVideoServer) Push(context.Context, *PushRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedVideoServer) mustEmbedUnimplementedVideoServer() {}

// UnsafeVideoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServer will
// result in compilation errors.
type UnsafeVideoServer interface {
	mustEmbedUnimplementedVideoServer()
}

func RegisterVideoServer(s grpc.ServiceRegistrar, srv VideoServer) {
	s.RegisterService(&Video_ServiceDesc, srv)
}

func _Video_Info_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VideoServer).Info(&videoInfoServer{stream})
}

type Video_InfoServer interface {
	Send(*InfoResponse) error
	Recv() (*InfoRequest, error)
	grpc.ServerStream
}

type videoInfoServer struct {
	grpc.ServerStream
}

func (x *videoInfoServer) Send(m *InfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *videoInfoServer) Recv() (*InfoRequest, error) {
	m := new(InfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Video_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Video/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Video_ServiceDesc is the grpc.ServiceDesc for Video service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Video_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Video_Push_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Info",
			Handler:       _Video_Info_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "video.proto",
}
